dist: xenial

language: python
python:
  - "3.8"
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - python .\innosoft_api\registro\management\commands\setup.py 
  - cd innosoft_api/
  - coverage run --source=. ./manage.py test
  - coverage xml
  - python-codacy-coverage -r innosoft_api/coverage.xml