dist: xenial

language: python
python:
  - "3.8"
install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - cd innosoft_api/
  - python manage.py makemigrations registro
  - python manage.py migrate registro
  - python manage.py group
  - python manage.py migrate
  - python manage.py makemigrations programa
  - python manage.py migrate programa
  - python manage.py makemigrations participacion
  - python manage.py migrate participacion
  - python manage.py test

