# Generated by Django 3.1.3 on 2020-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0002_auto_20201128_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
