# Generated by Django 3.1.3 on 2020-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0003_auto_20201128_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponencia',
            name='ponente',
        ),
        migrations.AddField(
            model_name='ponencia',
            name='ponente',
            field=models.ManyToManyField(related_name='datos_ponentes', to='programa.Ponente'),
        ),
    ]
