# Generated by Django 3.1.3 on 2020-11-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0004_auto_20201128_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponencia',
            old_name='ponente',
            new_name='ponentes',
        ),
    ]
