# Generated by Django 3.1.3 on 2020-12-12 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_auto_20201128_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='ponencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programa.ponencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
