# Generated by Django 3.1.3 on 2020-12-12 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0005_auto_20201128_1755'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participacion', '0002_auto_20201212_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('ponencia', 'usuario')},
        ),
    ]
