# Generated by Django 3.1.3 on 2020-12-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0003_auto_20201212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asiste',
            field=models.BooleanField(default=False),
        ),
    ]
