# Generated by Django 3.1.3 on 2020-12-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0004_auto_20201222_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR_Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.TextField()),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participacion.asistencia')),
            ],
        ),
    ]
