# Generated by Django 3.1.3 on 2020-12-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0005_qr_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='qr',
            field=models.TextField(default='asdasd'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QR_Asistencia',
        ),
    ]
