# Generated by Django 3.1.3 on 2020-12-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0006_auto_20201228_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='qr',
        ),
    ]
