# Generated by Django 3.1.3 on 2020-12-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0007_remove_asistencia_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='qr',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
