# Generated by Django 3.1.3 on 2020-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0008_asistencia_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='qr',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='qr_b64',
            field=models.TextField(blank=True),
        ),
    ]
