# Generated by Django 3.1.3 on 2021-01-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participacion', '0009_auto_20201228_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='qr_b64',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='code',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
